---
# tasks file for jenkins-node

- name: create group
  become: yes
  group:
    name: "{{ jenkins_node_user }}"
    state: present

- name: create user
  become: yes
  vars:
    # For whatever reason, passing a vaulted variable into the password_hash filter causes ansible to throw an error.
    # You must assign the vaulted variable to another variable first, then it will work properly with password_hash.
    unvaulted_jenkins_node_user_password: "{{ jenkins_node_user_password }}"
  user:
    name: "{{ jenkins_node_user }}"
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 4096
    groups: "{{ jenkins_node_user_groups }}"
    append: yes
    password: "{{ unvaulted_jenkins_node_user_password | password_hash('sha512') }}"

- name: add ansible_user to jenkins_user group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: "{{ jenkins_node_user }}"
    append: yes
  when: ansible_user_id != jenkins_node_user

- name: enable git-lfs
  become: yes
  become_user: "{{ jenkins_node_user }}"
  ansible.builtin.shell: git lfs install

- name: install pip from helper script
  become: yes
  become_user: "{{ jenkins_node_user }}"
  ansible.builtin.shell: python /tmp/get-pip.py
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version <= '7'

- name: install dependent pip packages
  become: yes
  become_user: "{{ jenkins_node_user }}"
  ansible.builtin.shell: pip install setuptools virtualenv -y

- name: install pip PyYAML
  become: yes
  become_user: "{{ jenkins_node_user }}"
  ansible.builtin.pip:
    name: PyYAML
    state: latest
    umask: "0022"

- name: install pip docker-compose latest
  become: yes
  become_user: "{{ jenkins_node_user }}"
  ansible.builtin.pip:
    name: docker-compose
    umask: "0022"

- name: create jenkins folder for workspaces
  become: yes
  file:
    path: "{{ jenkins_node_path }}"
    owner: "{{ jenkins_node_user }}"
    group: "{{ jenkins_node_user }}"
    mode: 0774
    state: directory

- name: install openjdk{{ jenkins_node_openjdk_major_version }} latest
  become: yes
  yum:
    # https://www.digitalocean.com/community/tutorials/how-to-install-java-on-centos-and-fedora
    # To install the JDK, you have to install java-###-openjdk-devel. Without the devel, you just get the JRE,
    # despite the VERY misleading name.
    name: "java-{{ jenkins_node_openjdk_major_version }}-openjdk-devel"
    state: latest
  when: jenkins_node_openjdk_full_version == "latest"

# https://access.redhat.com/solutions/98873
- name: install versionlock
  become: yes
  shell: yum install yum-plugin-versionlock -y
  when: jenkins_node_openjdk_full_version != "latest"

# Gotta let the package install/upgrade/downgrade if needed as the target version may have changed.
# The version lock is needed soley so a system wide yum update won't change the version of java.
- name: remove the version lock
  become: yes
  lineinfile:
    path: /etc/yum/pluginconf.d/versionlock.list
    state: absent
    line: "1:java-{{ jenkins_node_openjdk_major_version }}-openjdk-*"
  when: jenkins_node_openjdk_full_version != "latest"

- name: install locked java version
  become: yes
  yum:
    name:
      - "java-{{ jenkins_node_openjdk_major_version }}-openjdk-{{ jenkins_node_openjdk_full_version }}"
      - "java-{{ jenkins_node_openjdk_major_version }}-openjdk-headless-{{ jenkins_node_openjdk_full_version }}"
      - "java-{{ jenkins_node_openjdk_major_version }}-openjdk-devel-{{ jenkins_node_openjdk_full_version }}"
    state: present
    allow_downgrade: yes
  when: jenkins_node_openjdk_full_version != "latest"

- name: add the version lock back in
  become: yes
  lineinfile:
    path: /etc/yum/pluginconf.d/versionlock.list
    state: present
    line: "1:java-{{ jenkins_node_openjdk_major_version }}-openjdk-*"
  when: jenkins_node_openjdk_full_version != "latest"

# Other roles may install other versions of Java. This makes the default java executable point to the desired one here.
- name: switch to java {{ jenkins_node_openjdk_major_version }}
  become: yes
  alternatives:
    name: java
    link: /usr/bin/java
    path: /usr/lib/jvm/jre-{{ jenkins_node_openjdk_major_version }}-openjdk/bin/java

- name: install python-jenkins reqs
  become: yes
  become_user: "{{ jenkins_node_user }}"
  pip:
    name:
    - certifi
    - pbr
    state: latest
    executable: ~/.local/bin/pip

- name: install python-jenkins
  become: yes
  become_user: "{{ jenkins_node_user }}"
  pip:
    name: python-jenkins
    state: latest
    executable: ~/.local/bin/pip

- name: copy node creation script
  become: yes
  copy:
    src: create_jenkins_node_ssh.py
    dest: "{{ jenkins_node_path }}/create_jenkins_node_ssh.py"
    owner: "{{ jenkins_node_user }}"
    group: "{{ jenkins_node_user }}"
    mode: 0744

- name: add the node to the jenkins master
  become: yes
  become_user: "{{ jenkins_node_user }}"
  command: python {{ jenkins_node_path }}/create_jenkins_node_ssh.py "{{ jenkins_node_master_url }}" "{{ jenkins_node_master_user }}" "{{ jenkins_node_master_password }}" "{{ jenkins_node_credential }}" "{{ jenkins_node_name }}" "{{ jenkins_node_description }}" "{{ jenkins_node_labels }}" "{{ jenkins_node_host }}" "--num-executors={{ jenkins_node_executors }}" "--path={{ jenkins_node_path }}" "--port={{ jenkins_node_port }}" "--ca-cert={{ jenkins_node_master_ca_cert }}"
  # As of 2017-10-2, Ansible doesn't keep track what values were vaulted. Without no_log, an error would
  # cause the command to be displayed, which is not desirable.
  # 2019-12-02: You have two options. Use 'no_log: yes' or use a Jenkins credential object so Jenkins masks the output. I have opted for Jenkins to mask the output
  # as this is a command that fails often, and I'm tired of having to run the command by hand and removing no_log so I can see the output.
